name: Run Python Scraper and Notify

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (nur Quellcode)
        uses: actions/checkout@v4
        with:
          filter: 'blob:none'
          sparse-checkout: |        
            events.py
            requirements.txt
          fetch-depth: 1                    

      - name: Set up Python (mit Cache)
        uses: actions/setup-python@v5   # >= v4 nötig für cache
        with:
          python-version: "3.9"
          cache: 'pip'                  # aktiviert pip-Cache
          cache-dependency-path: requirements.txt 
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt \
              --no-color --disable-pip-version-check

      - name: Run Python Script
        run: python events.py

      - name: Check for Changes in events.json
        run: |
          if git diff --quiet events.json; then
            echo "Keine Änderungen in events.json, kein Commit erforderlich."
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          else
            echo "NO_CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Commit und Push JSON-Datei
        if: env.NO_CHANGES == 'false'
        run: |
          git config --global user.email "maikz@miltenyi.com"
          git config --global user.name "MaikZ91"
          export GIT_COMMITTER_NAME="MaikZ91"
          export GIT_COMMITTER_EMAIL="maikz@miltenyi.com"
          git add events.json
          git commit -m "Automatische Aktualisierung der Events [GitHub Actions]"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/MaikZ91/productiontools.git master
