name: Run Python Scraper and Notify

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "Keine Abhängigkeiten erforderlich"

      - name: Run Python Script
        run: python events.py

      - name: Commit und Push JSON-Datei
        run: |
          git config --global user.email "maikz@miltenyi.com"
          git config --global user.name "MaikZ91"
          export GIT_COMMITTER_NAME="MaikZ91"
          export GIT_COMMITTER_EMAIL="maikz@miltenyi.com"
          git add events.json
          git commit -m "Automatische Aktualisierung der Events [GitHub Actions]" || echo "Keine Änderungen zum Commit"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/MaikZ91/productiontools.git master

      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure SMTP for GMX
        run: |
          echo "defaults" > ~/.msmtprc
          echo "account gmx" >> ~/.msmtprc
          echo "host mail.gmx.net" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user maik.z@gmx.de" >> ~/.msmtprc
          echo "password ${{ secrets.GMX }}" >> ~/.msmtprc
          echo "from maik.z@gmx.de" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          echo "account default : gmx" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Create Email Content
        run: |
          echo "Subject: New Events Added" > event_changes.txt
          echo "To: maik.z@gmx.de" >> event_changes.txt
          echo "From: maik.z@gmx.de" >> event_changes.txt
          echo "" >> event_changes.txt
          echo "New events have been added to events.json:" >> event_changes.txt
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --unified=0 HEAD^ HEAD -- events.json | grep '^+' | grep -v '+++' >> event_changes.txt
          else
            echo "This is the first commit, no previous changes to show." >> event_changes.txt
          fi

      - name: Send Notification
        run: cat event_changes.txt | msmtp -a default maik.z@gmx.de
