name: Run Python Scraper

on:
  push:   # Startet das Skript automatisch, wenn du Änderungen am Code machst
    branches:
      - master  # Falls dein Haupt-Branch anders heißt, ändere das
  schedule:
    - cron: "0 * * * *"  # Führt das Skript jede Stunde aus
  workflow_dispatch:  # 🚀 Erlaubt das manuelle Starten des Workflows

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || echo "Keine Abhängigkeiten erforderlich"

      - name: Run Python Script
        run: python events.py

      - name: Commit und Push JSON-Datei
        run: |
          git config --global user.email "maikz@miltenyi.com"
          git config --global user.name "MaikZ91"
          git add events.json
          git commit -m "Automatische Aktualisierung der Events [GitHub Actions]" || echo "Keine Änderungen zum Commit"
          git push https://${{ secrets.PAT_TOKEN}}@github.com/MaikZ91/productiontools.git master
