name: Track Events

on:
  push:
    paths:
      - 'events.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure SMTP for GMX
        run: |
          echo "defaults" > ~/.msmtprc
          echo "account gmx" >> ~/.msmtprc
          echo "host mail.gmx.net" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user maik.z@gmx.de" >> ~/.msmtprc
          echo "password ${{ secrets.GMX }}" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          echo "account default : gmx" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Send notification
        run: |
          echo -e "Subject: New Events Added\nTo: maik.z@gmx.de\nFrom: maik.z@gmx.de\n\nNew events have been added to events.json." | msmtp -a default maik.z@gmx.de
