name: Track Events

on:
  push:
    paths:
      - 'events.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install msmtp
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure SMTP for GMX
        run: |
          echo "defaults" > ~/.msmtprc
          echo "account gmx" >> ~/.msmtprc
          echo "host mail.gmx.net" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user maik.z@gmx.de" >> ~/.msmtprc
          echo "password ${{ secrets.GMX }}" >> ~/.msmtprc
          echo "from maik.z@gmx.de" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          echo "account default : gmx" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

      - name: Get added events
        run: |
          echo "Subject: New Events Added" > event_changes.txt
          echo "To: maik.z@gmx.de" >> event_changes.txt
          echo "From: maik.z@gmx.de" >> event_changes.txt
          echo "" >> event_changes.txt
          echo "New events have been added to events.json:" >> event_changes.txt
          git diff --unified=0 HEAD^ HEAD -- events.json | grep '^+' | grep -v '+++' >> event_changes.txt

      - name: Send notification
        run: |
          cat event_changes.txt | msmtp -a default maik.z@gmx.de
