name: Send WhatsApp Group Message (Python)

# Cron: Mo & Do 09:00 Europe/Berlin → UTC+2 → 07:00 UTC
on:
  schedule:
    - cron: '0 7 * * 1,4'

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        working-directory: send-whatsapp-py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nachricht senden
        working-directory: send-whatsapp-py
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: python send_whatsapp.py
